version: "3.8"

services:
  seed_x_api:
    build:
      context: ./seed_x
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: sh -c "python manage.py flush --no-input && python manage.py test"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14.1-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

volumes:
  postgres_data_test:
