# Generated by Django 4.2 on 2023-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(max_length=50, verbose_name='tag type')),
                ('value', models.CharField(max_length=50, verbose_name='tag value')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='tag short name')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'unique_together': {('tag_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='row')),
                ('col', models.IntegerField(verbose_name='row')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('INVALID', 'INVALID')], max_length=7, verbose_name='status')),
                ('tags', models.ManyToManyField(to='core.tag', verbose_name='tags')),
            ],
        ),
    ]
